# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS   := n3_receiver
BPF_TARGETS    := veth_kern
BPF_TARGETS    += nic_kern

LDLIBS += -lpthread

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
